excerpt_separator: "<!--more-->"
highlighter: pygments
markdown: kramdown
url: http://hexadevti.github.io/hexadevti.github.io/
title: Gentrop Blog
email: luciano.faria@gentrop.com
author: Luciano Faria
description: My awesome new site
gems : [jekyll-paginate]
paginate: 4
google_analytics: 
